version: "3.9"

services:
  client:
    image: clientapp
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - mern-network
  order:
    image: orderserv
    container_name: order
    ports:
      - "8070:8070"
    networks:
      - mern-network
  user:
    image: userserv
    container_name: user
    ports:
      - "8050:8050"
    networks:
      - mern-network
  auth:
    image: authserve
    container_name: auth
    ports:
      - "8080:8080"
    networks:
      - mern-network
  inventory:
    image: inventoryserve
    container_name: inventory
    ports:
      - "8060:8060"
    networks:
      - mern-network

  payment:
    image: paymentserve
    container_name: payment
    ports:
      - "9000:9000"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
