version: "3.9"

services:
  client:
    image: clientapp
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - mern-network
  order:
    image: orderserv
    container_name: order
    ports:
      - "8070:8070"
    networks:
      - mern-network

  auth:
    image: authserv
    container_name: auth
    ports:
      - "8080:8080"
    networks:
      - mern-network

  inventory:
    image: inventoryserv
    container_name: inventory
    ports:
      - "8060:8060"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
